import jsPDF from "jspdf";

export interface ShareSummaryData {
  title: string;
  lines: { label: string; value: string }[];
  areaBreakdown?: { area: string; value: string }[];
  companyName?: string;
}

export function generateShareText(data: ShareSummaryData): string {
  const parts = [data.title, "------------------"];
  data.lines.forEach((l) => parts.push(`${l.label}: ${l.value}`));
  if (data.areaBreakdown && data.areaBreakdown.length > 0) {
    parts.push("", "Area Breakdown:");
    data.areaBreakdown.forEach((a) => parts.push(`  ${a.area}: ${a.value}`));
  }
  return parts.join("\n");
}

export function shareViaWhatsApp(text: string) {
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
}

export function shareViaEmail(subject: string, text: string) {
  window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text)}`, "_blank");
}

export function shareViaSMS(text: string) {
  window.open(`sms:?&body=${encodeURIComponent(text)}`, "_blank");
}

export function generateSummaryPDF(data: ShareSummaryData): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Company name
  if (data.companyName) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(data.companyName, pageWidth / 2, y, { align: "center" });
    y += 10;
  }

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, pageWidth / 2, y, { align: "center" });
  y += 8;

  // Date
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`, pageWidth / 2, y, { align: "center" });
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // Summary lines
  doc.setTextColor(30, 30, 30);
  data.lines.forEach((line) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(line.label, 25, y);
    doc.setFont("helvetica", "bold");
    doc.text(line.value, pageWidth - 25, y, { align: "right" });
    y += 9;
  });

  // Area breakdown
  if (data.areaBreakdown && data.areaBreakdown.length > 0) {
    y += 4;
    doc.setDrawColor(220, 220, 220);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Area Breakdown", 25, y);
    y += 8;

    data.areaBreakdown.forEach((a) => {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);
      doc.text(a.area, 30, y);
      doc.setFont("helvetica", "bold");
      doc.text(a.value, pageWidth - 25, y, { align: "right" });
      y += 8;
    });
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by MoneyMate", pageWidth / 2, y, { align: "center" });

  return doc.output("blob");
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
